### PR TITLE
Add missing ceph-radosgw certificates, ceilometer:amqp and ceilometer:identity-credentials relations

### PR DESCRIPTION
**Pull request by DavidSpek**

### CODE REVIEW

**Comment by DavidSpek** [comment]
Also, I was wondering if there is a reason why memcached is set to ` series: bionic`.

**Comment by DavidSpek** [comment]
I just noticed the following relations are also missing for a working bundle:
```
- - ceilometer:amqp
  - rabbitmq-server:amqp
- - ceilometer:identity-credentials
  - keystone:identity-credentials
```

The documentation states `ceilometer:identity-service` and for Queens `ceilometer:identity-credentials`. However, the relation will show up as missing when using `ceilometer:identity-service` but works with `ceilometer:identity-credentials`.

**Comment by AurelienLourot** [comment]
Yes it looks like you're right according to https://jaas.ai/u/openstack-charmers-next/ceilometer

**Comment by ajkavanagh** [comment]
> Also, I was wondering if there is a reason why memcached is set to ` series: bionic`.

It's probably just that there was a point in time when the memcached charm didn't support focal, but the other charms did, so it was pinned to bionic so that the bundle could be deployed.

**Pull request merged**
