### PR TITLE
Fix Keystone API version detection, migrate to `openrc`

### PR DESCRIPTION
**Pull request by fnordahl**
Fix Keystone API version detection

Rename `novarc_auto` to `openrc` and update documentation

Add `openrc` symlink and update documentation    

Fixes LP: #1760806

### CODE REVIEW

**Comment by sfeole** [comment]
Good updates, with these updates there is the old legacy 'novarc' in the same directory, does that need to be around anymore do we rely on that for anything? :  https://github.com/openstack-charmers/openstack-bundles/blob/master/development/shared/novarc

**Comment by fnordahl** [comment]
@sfeole good point.

Maybe we should redecorate the name while at it. The upstream name for this has been `openrc` for a long while, let's match that.

**Comment by andrewdmcleod** [comment]
lgtm also, in addition to conversation with @fnordahl on irc: rename to openrc, create link to novarc, add deprecation notice if script name is novarc.

**Comment by sfeole** [comment]
So this is a pretty significant change, I'm ok with it, but all of our docs will be stale after this lands. All of the README.md's will have to be updated to source openrc vs novarc_auto.   
Giving we just went through weeks of queens docs updates. That should probably be done in addition to this change.

**Comment by sfeole** [comment]
Thanks for the updates, LGTM don't see any problems here.

**Pull request merged**
